
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      - db
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules: