
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  coderunner_cpp:
    build:
      context: ./backend/docker/cpp
    container_name: coderunner_cpp
    volumes:
      - ./tmp:/code
    security_opt:
      - no-new-privileges
    mem_limit: 512m
    cpu_quota: 50000
    read_only: true

  coderunner_java:
    build:
      context: ./backend/docker/java
    container_name: coderunner_java
    volumes:
      - ./tmp:/code
    security_opt:
      - no-new-privileges
    mem_limit: 512m
    cpu_quota: 50000
    read_only: true
    command: java -cp /code Main   

  coderunner_python:
    build:
      context: ./backend/docker/python
    container_name: coderunner_python
    volumes:
      - ./tmp:/code
    security_opt:
      - no-new-privileges
    mem_limit: 512m
    cpu_quota: 50000
    read_only: true

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
