version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock 
    env_file: backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      LANGSMITH_TRACING: true
      LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
      LANGSMITH_API_KEY: "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" # Use an environment variable
      LANGSMITH_PROJECT: "pr-unnatural-sultan-1"
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&  
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"  # Removed unnecessary quotes around daphne

  frontend:
    build:
      context: ./frontend
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
