version: "3.8"
services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host  
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:
